<a href="https://colab.research.google.com/github/harshavardhini034-creator/Data-Analysis-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [ ]:
#DAY-1
#Creation of 1D array
import numpy as np
numbers=np.array([5,10,15,20,30]) #1D array
print(numbers)

[ 5 10 15 20 30]


In [ ]:
#(arr.ndim) is the method to check the dimension of the array
print(numbers.ndim)

1


In [ ]:
print(numbers.shape) #tells us no.of rows & columns


(5,)


In [ ]:

#2D array creation
arr = np.array([[10,20,30],
               [40,50,60]
               ])
print(arr)

[[10 20 30]
 [40 50 60]]


In [ ]:
print(arr.ndim)


2


In [ ]:
print(arr.shape)


(2, 3)


In [ ]:
#3D array creation
arr_ = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])
print(arr_)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr_.ndim)


3


In [ ]:
print(arr_.shape)


(2, 2, 3)


In [ ]:

#(np.arange) for generating a sequence of numbers
num = np.arange(1,10)
print(num)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#for odd numbers
num = np.arange(1,15,2) # (start,stop,step)
print(num)

[ 1  3  5  7  9 11 13]


In [ ]:
# For zeros we use the method np.zeros with the size
#1D
zeroes_1d = np.zeros(4)
print(zeroes_1d)

[0. 0. 0. 0.]


In [ ]:

#2D
zeroes_2d = np.zeros((2,3))
print(zeroes_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#3D
zeroes_3d = np.zeros((2,2,3))
print(zeroes_3d)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#For ones
#1D
ones_1d = np.ones(6)
print(ones_1d)

[1. 1. 1. 1. 1. 1.]


In [ ]:

#2D
ones_2d = np.ones((2,3))
print(ones_2d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#3D
ones_3d = np.ones((2,2,3))
print(ones_3d)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#Array of any constant value means user defined values
#1D
full_1d = np.full(4,8) #Here 4 means no.of times we want(count) and 8 means which number we want
print(full_1d)

[8 8 8 8]


In [ ]:
#2D
full_2d = np.full((2,3),5) #Here (2,3) means 2 rows and 3 columns and 5 means which number we want
print(full_2d)

[[5 5 5]
 [5 5 5]]


In [ ]:
#3D
full_3d = np.full((2,2,3),7) #Here (2,2,3) means 2 rows and 2 columns and 3 means height , 7 is the number
print(full_3d)


[[[7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]]]


In [ ]:


# reshape() is the method is convert 1D to 2D or 2D to 3D or rows to columns or columns to rows
#1D
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a=arr.reshape(2,6) #Here value error will be occur bcoz when we are assiging we have to check the possibility from the array
print(a)

ValueError: cannot reshape array of size 10 into shape (2,6)

In [ ]:


a=arr.reshape(2,5) # or (5,2) (10,1) (1,10)........
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#2D
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print("--------------------------")
a=arr.reshape((2,5))
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
--------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#3D
arr = np.arange(1,11).reshape(5,2,1) (5 2d tables , 2 rows , column 1)
print(arr)

SyntaxError: invalid decimal literal (1509032650.py, line 2)

In [ ]:

#Task
#containing nums from 10 to 50
arr_= np.arange(10,50,5)
print(arr_)

[10 15 20 25 30 35 40 45]


In [ ]:
#even numbers from 2 to 30
num = np.arange(0,30,2)
print(num)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [ ]:
#empids from 1001 to 1020
import numpy as np
num = np.arange(1001,1021)
print(num)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020]


In [ ]:
# nums down from 50 to 1
down=np.arange(50,1,-1)
print(down)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2]


In [ ]:
import numpy as np
roll_numbers = np.array([101,102,103,104,105,106,107,108])
print(roll_numbers)

[101 102 103 104 105 106 107 108]


In [ ]:
#use method reshape to change 2D and 3D
#2D
a=roll_numbers.reshape(2,4) # (1,8) (8,)
print(a)

[[101 102 103 104]
 [105 106 107 108]]


In [ ]:


#3D
arr = np.arange(101,109).reshape(1,2,4) #(1 rows , 2 columns , height 4)
print(arr)

[[[101 102 103 104]
  [105 106 107 108]]]


In [ ]:

#3D
arr = np.arange(101,109).reshape(1,4,2)
print(arr)

[[[101 102]
  [103 104]
  [105 106]
  [107 108]]]


In [ ]:

#3D
arr = np.arange(101,109).reshape(4,1,2)
print(arr) #Possibilities (1,2,4) (1,4,2) (2,1,4) (4,1,2) (4,2,1) (1,1,8) (8,1,1)

[[[101 102]]

 [[103 104]]

 [[105 106]]

 [[107 108]]]


In [ ]:

#elements of 7 as 10 times
#1D
full_ = np.full(10,7)
print(full_)

[7 7 7 7 7 7 7 7 7 7]


In [ ]:
#2D
full2_ = np.full((2,5),7)
print(full2_)

[[7 7 7 7 7]
 [7 7 7 7 7]]


In [ ]:
full2_ = np.full((5,2),7)
print(full2_)

[[7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]]


In [ ]:
#3D
full3_ = np.full((5,2,1),7)
print(full3_)

[[[7]
  [7]]

 [[7]
  [7]]

 [[7]
  [7]]

 [[7]
  [7]]

 [[7]
  [7]]]


In [ ]:
import numpy as np
arr = np.array([1.2,2.5,6.9,5,4,6],dtype="int")
print(arr)
print(arr.dtype)

[1 2 6 5 4 6]
int64


In [ ]:
import numpy as np
arr = np.array([1.2,2.5,6.9,5,4,6],dtype="float")
print(arr)
print(arr.dtype)

[1.2 2.5 6.9 5.  4.  6. ]
float64


In [ ]:
import numpy as np
arr = np.array([1.2,2.5,6.9,5,4,"a"],dtype="str")
print(arr)
print(arr.dtype) #to identify array in which datatype (arr.dtype)

['1.2' '2.5' '6.9' '5' '4' 'a']
<U3


In [ ]:


import numpy as np
arr = np.array(["Priya","Laxmi","Mahesh","Deepa","Pravallika"],dtype="str")
print(arr)


['Priya' 'Laxmi' 'Mahesh' 'Deepa' 'Pravallika']


In [ ]:

#Day-3
#linspace() -
import numpy as np
arr = np.linspace(0,10,4) #(start,stop, differnce)
print(arr)

[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
arr_ = np.array([10,20,30,40])
print(arr_.shape) #Shape is an attribute and reshape is a method

(4,)


In [ ]:
import numpy as np
# ravel() - to compress multi-dimensional array to 1D
new_arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(new_arr)
result = new_arr.ravel()
print(result)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
result = new_arr.ravel()
print(result)

[1 2 3 4 5 6]


In [ ]:
arr = np.arange(1,10).reshape(3,3,1)
print(arr)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [ ]:
result = arr.ravel()
print(result)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#Transpose the array :- rows to columns and columns to rows
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
r = arr.transpose() #or .T alse we can use
print(r)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Datatype Conversion - astype()
arr = np.array([10,20,30,40])
arr_ = arr.astype(float) # Here Iam changing int to float
print(arr_)
print(arr_.dtype)

[10. 20. 30. 40.]
float64


In [ ]:
#Indexing
arr = np.array([10,20,30,40,50]) #1D
print(arr[0:2])
print(arr[-2:])
print(arr[-3:-1])
print(arr[:4])

[10 20]
[40 50]
[30 40]
[10 20 30 40]


In [ ]:
arr = np.arange(1,10).reshape(3,3) #2d
print(arr)
print("_______________")
print(arr[0,2]) # Indexing for 2D
print("_______________")
print(arr[1,1])
print("_______________")
print(arr[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
_______________
3
_______________
5
_______________
8


In [ ]:
#Slicing
print(arr[0:2]) # 0 row to 1st row

[[1 2 3]
 [4 5 6]]


In [ ]:

print(arr[0:3,0:1]) # 3 rows and only 1 column

[[1]
 [4]
 [7]]


In [ ]:
#Modifications
arr = np.arange(1,16)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
arr[6] = 229 #Here iam changing 6th index value
print(arr)

[  1   2   3   4   5   6 229   8   9  10  11  12  13  14  15]


In [ ]:
arr[2:5] = 99 #To change multiple values
print(arr)

[  1   2  99  99  99   6 229   8   9  10  11  12  13  14  15]


In [ ]:
# Insert()
arr = np.arange(1,11)
print(arr)
print("---------------")
n = np.insert(arr,3,85) #Here iam inserting 85 to 3rd index
print(n)

[ 1  2  3  4  5  6  7  8  9 10]
---------------
[ 1  2  3 85  4  5  6  7  8  9 10]


In [ ]:
# to insert multiple values
arr = np.arange(1,11)
print(arr)
print("---------------")
arr_ = np.insert(arr,3,[20,30,40])
print(arr_)

[ 1  2  3  4  5  6  7  8  9 10]
---------------
[ 1  2  3 20 30 40  4  5  6  7  8  9 10]


In [ ]:
#Delete()
arr = np.arange(1,11)
print(arr)
print("---------------")
arr_ = np.delete(arr,4) # 4th element index deleting
print(arr_)
print("----------------")
#For deleting multiple values

[ 1  2  3  4  5  6  7  8  9 10]
---------------
[ 1  2  3  4  6  7  8  9 10]
----------------


In [ ]:
# TASK
# 1) NpArray containg 10 equally spaced numbers between 0 to 100 using np.linspace
import numpy as np
arr = np.linspace(0,100,10)
print(arr)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [ ]:
#2) 15 equally spaced btw 1 to 50
import numpy as np
arr = np.linspace(1,50,15)
print(arr)

[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]


In [ ]:
#creating
arr = np.array([10,20,30,40,50,60,70])
print(arr)

[10 20 30 40 50 60 70]


In [ ]:
#access first element
print(arr[0])

10


In [ ]:
#access last element
print(arr[-1])

70


In [ ]:
#access the 4th element
print(arr[3])

40


In [ ]:
#Acess the element 60
print(arr[5])

60


In [ ]:
#Slicing creation
arr_ = np.array([10,20,30,40,50,60,70,80])
print(arr_)

[10 20 30 40 50 60 70 80]


In [ ]:
#Extract the first 4 elements
print(arr_[0:4])

[10 20 30 40]


In [ ]:
#From index 2 to 5
print(arr_[2:6])

[30 40 50 60]


In [ ]:
#the last 3 elements
print(arr_[-3:])

[60 70 80]


In [ ]:
#Every Alternate elements
arr_ = np.array([10,20,30,40,50,60,70,80])
for i in range(0,len(arr_)-1,2):
  print(arr_[i],end = " ")

10 30 50 70 

In [ ]:
#or
print(arr_[0:7:2])


[10 30 50 70]


In [ ]:
#2D Array
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]])
print(arr)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
#to access 50, 30, 70
print(arr[1,1])
print(arr[0,2])
print(arr[2,0])

50
30
70


In [ ]:
#The complete 2nd row
print(arr[1])


In [ ]:
#the complte 3rd row
print(arr[2])

In [ ]:
#Generate 5 equally spaced values between 0 and 100 using linespace()
import numpy as np
arr = np.linspace(0,100,5)
print(arr)

[  0.  25.  50.  75. 100.]


In [ ]:
#Display the transpose of the array
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Display 4x4 identity matrix
import numpy as np
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Generate 10 random values between 0 and 1
import numpy as np
arr_ = np.random.random(10)
print(arr_)

[0.66778677 0.92194303 0.51610203 0.07216449 0.91294588 0.3788207
 0.77658132 0.69241539 0.76763353 0.33387048]


In [ ]:
#Generate 5 random values between 50 and 100 using uniform()
import numpy as np
ran_ = np.random.uniform(50,100,5)
print(ran_)

[66.21383307 54.19558721 85.48933805 56.13058773 79.62740633]


In [ ]:
#Randomly select 5 marks using choice()
arr = np.array([10, 20, 30, 40, 50,60,70,80,90,100])
result = np.random.choice(arr, 5)
print(result)


[30 20 40 90 30]


In [ ]:
#Use shuffle() to randomly rearrang the students marks
np.random.shuffle(arr)
print(arr)

[ 60  30  80  90 100  40  70  50  10  20]


In [ ]:
# Use permutation() to create a randomly rearranged version
result = np.random.permutation(arr)
print("Original:", arr)

Original: [ 60  30  80  90 100  40  70  50  10  20]


In [ ]:
#DAY-5
# Aggrigations and Statistical Operations(sum,min,max,mean,median,std,var,argmax,argmin)
import numpy as np
arr = np.array([10,20,30,40,50])#1D
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.percentile(arr,50))

150
10
50
30.0
30.0
14.142135623730951
200.0
30.0


In [ ]:
#Percentile & Quantile
arr = np.array([10,20,30,40,50])
print(np.percentile(arr,100))
np.quantile(arr,1) #Quantile is opposite to the percentile(percentile btw 0 to 100 amd quantile btw proportion 0 and 1)


50.0


np.int64(50)

In [ ]:
#Argmax - means it returns the position of the highest value
#Argmin
arr = np.array([10,30,35,90,5,40])#indexing 0 1 2 3
print(np.argmax(arr))
print(np.argmin(arr))


3
4


In [ ]:
#Log10
arr = np.array([10,100,1000])
print(np.log10(arr))
#Log2
print(np.log(arr))
print(np.log(2))
print("-----------------------")
#Round()
arr = np.array([10.23,52.6,45.52,30.31])
print(np.round(arr))
arr = np.array([10.235,52.628,45.547])
print(np.round(arr,2))
print("-----------------------")
#Floor() - for lower limit
arr = np.array([10.2,108,209,32.9])
print(np.floor(arr))
print("-----------------------")
#Ceil() - for upper limit
arr = np.array([10.2,108,209,32.9])
print(np.ceil(arr))
print("-----------------------")
#abs() - it is used to convert negtive to positive number
arr = np.array([2,-5,3,9,-8])
print(np.abs(arr))
print("-------------------------")
#Sort()
arr = np.array([15,25,75,10,35])
result = np.sort(arr) #Asec order
print(result)
print("--------------")
arr = np.array([15,25,75,10,35])
result = np.sort(arr)[::-1] #Dsec order
print(result)

[1. 2. 3.]
[2.30258509 4.60517019 6.90775528]
0.6931471805599453
-----------------------
[10. 53. 46. 30.]
[10.24 52.63 45.55]
-----------------------
[ 10. 108. 209.  32.]
-----------------------
[ 11. 108. 209.  33.]
-----------------------
[2 5 3 9 8]
-------------------------
[10 15 25 35 75]
--------------
[75 35 25 15 10]


In [ ]:
#For 2D
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.percentile(arr,50))



210
10
60
35.0
35.0
17.07825127659933
291.6666666666667
35.0


In [ ]:
arr = np.array([10,20,30,40,50])
print(np.percentile(arr,100))
np.quantile(arr,1)#Here 1 means 100 percentage

50.0


np.int64(50)

In [ ]:
arr = np.array([55,40,30,80,50,60]).reshape(2,3)
print(arr)
print(np.argmax(arr))
print(np.argmin(arr))

[[55 40 30]
 [80 50 60]]
3
2


In [ ]:
#Log10
arr = np.array([10,20,30,40,50,60]).reshape(2,3)
print(np.log10(arr))
print("--------------------------")
#Log
print(np.log(arr))
print("--------------------------")
#Round
arr = np.array([10.23,52.6,45.52,30.31])
print(np.round(arr))
arr = np.array([10.235,52.628,45.547])
print(np.round(arr,2))
print("--------------------------")
#Floor() - for lower limit
arr = np.array([10.2,108,209,32.9]).reshape(2,2)
print(arr)
print(np.floor(arr))
print("-----------------------")
#Ceil() - for upper limit
arr = np.array([10.2,108,209,32.9]).reshape(2,2)
print(np.ceil(arr))
print("-----------------------")
#Abs()
arr = np.array([10,-15,-48,23]).reshape(2,2)
print(arr)
print(np.abs(arr))
#Sort()
arr = np.array([15,25,75,10,35,85]).reshape(2,3)
result = np.sort(arr) #Asec order
print(result)
print("--------------")
arr = np.array([15,25,75,10,35,85]).reshape(2,3)
result = np.sort(arr)[::-1] #Dsec order
print(result)

[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]
--------------------------
[[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]]
--------------------------
[10. 53. 46. 30.]
[10.24 52.63 45.55]
--------------------------
[[ 10.2 108. ]
 [209.   32.9]]
[[ 10. 108.]
 [209.  32.]]
-----------------------
[[ 11. 108.]
 [209.  33.]]
-----------------------
[[ 10 -15]
 [-48  23]]
[[10 15]
 [48 23]]
[[15 25 75]
 [10 35 85]]
--------------
[[10 35 85]
 [15 25 75]]


In [ ]:
#Row wise Sum(axis= 0)
print(np.sum(arr,axis=0))

[ 25  60 160]


In [ ]:
#Column wise Sum(axis= 1)
print(np.sum(arr,axis=1))

[115 130]


In [ ]:
#TASK
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
#2
marks = np.array([45, 78, 92, 56, 88, 67, 34])
print(np.min(marks), np.max(marks))
#3
sales = np.array([12000, 15000, 18000, 11000, 20000])
print(np.mean(sales))
#4
data = np.array([10, 20, 30, 40, 50])
print(np.var(data))
#5
marks = np.array([60, 70, 80, 90, 100])
print(np.std(marks))
#6
marks = np.array([35, 42, 55, 60, 68, 72, 80, 85, 95, 100])
print(np.percentile(marks, 50))
#7
salary = np.array([25000, 30000, 35000, 40000, 45000, 50000])
print(np.quantile(salary, [0.25, 0.75]))
#8
sales = np.array([15000, 22000, 18000, 35000, 27000, 12000])
print(np.argmax(sales))
#9
temperatures = np.array([32, 28, 35, 25, 30, 22, 38])
print(np.argmin(temperatures))
#10
arr = np.array([1, 10, 100, 1000, 10000])
print(np.log10(arr))
#11
arr = np.array([1, 2, 4, 8, 16, 32])
print(np.log2(arr))
#12
arr = np.array([1, 2, 3, 4, 5])
print(np.log(arr))
#13
arr = np.array([4, 9, 16, 25, 36, 49])
print(np.sqrt(arr))
#14
prices = np.array([12.45,23.67,45.89,56.12,78.95])
print(np.round(prices))
#15
arr = np.array([10.2,15.8,20.4,25.9,30.1])
print(np.floor(arr))
#16
arr = np.array([10.2,15.8,20.4,25.9,30.1])
print(np.ceil(arr))


150
34 92
15200.0
200.0
14.142135623730951
70.0
[31250. 43750.]
3
5
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4. 5.]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[2. 3. 4. 5. 6. 7.]
[12. 24. 46. 56. 79.]
[10. 15. 20. 25. 30.]
[11. 16. 21. 26. 31.]


In [ ]:
#DAY-6
#Concatenate and Stack
#For 1D
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.concatenate((arr1,arr2))
print(result)
print(result.ndim)

[10 20 30 40 50 60]
1


In [ ]:
#Concatenate - np.concatenate and Stack - np.stack
#For 2D
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.stack((arr1,arr2))
print(result)
print(result.ndim)

[[10 20 30]
 [40 50 60]]
2


In [ ]:
#Horizontal concatenate(axis=1) - Means it adds the 2nd array beside the 1st array
import numpy as np
arr1 = np.array([
    [10,20],
    [30,40]])
arr2 = np.array([
    [50,60],
    [70,80]
])
result = np.concatenate((arr1, arr2), axis=1)
print(result)
print(result.ndim)

[[10 20 50 60]
 [30 40 70 80]]
2


In [ ]:
#Vertical concatenate(axis=0) - Means it adds the 2nd array down to the 1st array
import numpy as np
arr1 = np.array([
    [10,20],
    [30,40]])
arr2 = np.array([
    [50,60],
    [70,80]
])
result = np.concatenate((arr1, arr2), axis=0)
print(result)
print(result.ndim)



[[10 20]
 [30 40]
 [50 60]
 [70 80]]
2


In [ ]:
# Stack - np.stack : it changes dimensions
import numpy as np
arr1 = np.array([10,20,30]) #Here it is changing 1D to 2D
arr2 = np.array([40,50,60])
result = np.stack((arr1,arr2),axis=0) #for rows
print(result)
print(result.ndim)

[[10 20 30]
 [40 50 60]]
2


In [ ]:
# 1D to 2D - for columns
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.stack((arr1,arr2),axis=1)
print(result)
print(result.ndim)

[[10 40]
 [20 50]
 [30 60]]
2


In [ ]:
#2D to 3D -For rows
import numpy as np
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])
arr2 = np.array([
    [10,20,30],
    [40,50,60]
])
result = np.stack((arr1,arr2),axis=0)
print(result)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [ ]:
#2D to 3D - For columns
import numpy as np
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [8,9,0]
])
arr2 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
result = np.stack((arr1,arr2),axis=1) #Here all 1st rows will be one array and all 2nd rows will be another array
print(result)

[[[ 1  2  3]
  [10 20 30]]

 [[ 4  5  6]
  [40 50 60]]

 [[ 8  9  0]
  [70 80 90]]]


In [ ]:
#VStack - Means vertical stack - dont need to specify axis
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.vstack((arr1,arr2))
print(result)
print(result.ndim)#Here it changes 1D to 2D



[[10 20 30]
 [40 50 60]]
2


In [ ]:

#2D
arr1 = ([
    [1,2,3],
    [4,5,6]
])
arr2 = ([
    [10,20,30],
    [40,50,60]
])
result = np.vstack((arr1,arr2)) #from 2D the dimensions will not change...only 1D will change dimension..it is an exceptional case
print(result)
print(result.ndim)


[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
2


In [ ]:
#3D
arr1 = np.arange(1,10).reshape(3,3,1)
arr2 = np.arange(21,30).reshape(3,3,1)
result = np.vstack((arr1,arr2))
print(result)
print(result.ndim)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[21]
  [22]
  [23]]

 [[24]
  [25]
  [26]]

 [[27]
  [28]
  [29]]]
3


In [ ]:
#HStack
#1D
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.hstack((arr1,arr2))
print(result)
print(result.ndim)

[10 20 30 40 50 60]
1


In [ ]:

#2D
arr1 = ([
    [1,2,3],
    [4,5,6]
])
arr2 = ([
    [10,20,30],
    [40,50,60]
])
result = np.vstack((arr1,arr2))
print(result)
print(result.ndim)


[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
2


In [ ]:
import numpy as np
stu_id = np.array([
    [1, 2],
    [3, 4]
])
marks = np.array([
    [25, 35],
    [45, 55]
])
result = np.concatenate((stu_id, marks), axis=1)
print(result)
print(result.ndim)
Output:

SyntaxError: invalid syntax (1441288101.py, line 13)

In [ ]:
#Split
#1D
import numpy as np
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,3) #Equal split
print(result)


[array([10, 20]), array([30, 40]), array([50, 60])]


In [ ]:
#Customized split
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,[2,4])
print(result)
print("------------------------------")#Partitioning
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,[1,3,5])
print(result)


[array([10, 20]), array([30, 40]), array([50, 60])]
------------------------------
[array([10]), array([20, 30]), array([40, 50]), array([60])]


In [ ]:
#Split on 2D
arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr)
print("---------------------")
result = np.split(arr,2,axis=0)
print(result)


[[10 20 30]
 [40 50 60]]
---------------------
[array([[10, 20, 30]]), array([[40, 50, 60]])]


In [ ]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr)
print("----------------------")
result = np.split(arr,3,axis=1)
print(result)


[[10 20 30]
 [40 50 60]]
----------------------
[array([[10],
       [40]]), array([[20],
       [50]]), array([[30],
       [60]])]


In [ ]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr)
print("----------------------")
result = np.split(arr,[1,3],axis=1)
print(result)


[[10 20 30]
 [40 50 60]
 [70 80 90]]
----------------------
[array([[10],
       [40],
       [70]]), array([[20, 30],
       [50, 60],
       [80, 90]]), array([], shape=(3, 0), dtype=int64)]
