<a href="https://colab.research.google.com/github/HarikaKirlampalli/Data-Analytics-Journey/blob/main/Numpy_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Create a 1D NumPy array containing the values [10, 20, 30, 40, 50] and display the number of dimensions, shape, size, and data type
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(np.ndim(arr))
print(np.shape(arr))
print(arr.dtype)
print(arr.size)

[10 20 30 40 50]
1
(5,)
int64
5


In [2]:
# 2. Create a 2D array containing numbers from 1 to 12 arranged in 3 rows and 4 columns,
# and create a 3D array containing numbers from 1 to 24 arranged as 2 x 3 x 4
import numpy as np
arr = np.arange(1,13).reshape((3,4))
print(arr)
print("---------------------------")
arr = np.arange(1,25).reshape(2,3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------------------------
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
#3. Create 1D, 2D, and 3D arrays containing only zeros with suitable dimensions
zero1 = np.zeros(5)
print(zero1)
print("------------------")
#2D
zero2 = np.zeros((3,4))
print(zero2)
print("-----------------")
#3D
zero3 = np.zeros((2,3,4))
print(zero3)


[0. 0. 0. 0. 0.]
------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [3]:
# 4. Create a 2 x 3 array containing only ones and display its dimensions and shape
one_ = np.ones((2,3))
print(one_)
print(np.ndim(one_))
print(np.shape(one_))

[[1. 1. 1.]
 [1. 1. 1.]]
2
(2, 3)


In [ ]:
# 5. Create a 3 x 4 array where every element is 7, and create a 4 x 4 square
# matrix with 1s on the main diagonal and 0s elsewhere 7
#3x4
full_ = np.full((3,4),7)
print(full_)
print("--------------")
#4x4 identiy
arr = np.eye(4)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
--------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
# 6. Generate five random decimal values between 0 and 1 and a 2 x 3 array of random decimal values between 0 and 1
import numpy as np
print(np.random.random(5))
print(np.random.random((2, 3)))

[0.81623467 0.58812147 0.72597996 0.65797554 0.0421691 ]
[[0.37333717 0.22232442 0.28944233]
 [0.69424395 0.33100618 0.00201414]]


In [5]:
# 7. Generate a 3 x 3 array of random values between 10 and 50
import numpy as np
arr = np.random.randint(10, 51, (3, 3))
print(arr)

[[42 31 17]
 [30 26 42]
 [28 49 32]]


In [ ]:
# 8. Generate a 2 x 4 array of random values following a standard normal distribution
arr = np.random.random((2,4))
print(arr)

[[0.9391108  0.5863139  0.07131126 0.17660445]
 [0.61544945 0.14396092 0.63650209 0.6490227 ]]


In [ ]:
# 9. Randomly select 3 colors
colors = ["Red","Blue","Green","Yellow","Black"]
print(np.random.choice(colors,3))

['Black' 'Blue' 'Red']


In [9]:
# 10. Generate five random numbers, set a fixed starting point for the random generator, and generate them again. Verify that both sets are identical.
np.random.seed(10)
a = np.random.random(5)
np.random.seed(10)
b = np.random.random(5)
print(a)
print(b)


[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]


In [10]:
# 11. Create an array containing all numbers from 5 to 50 with a step of 5
arr = np.arange(5, 51, 5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


In [11]:
# 12. Create one version where the original array's order is changed randomly,
# and another version where a randomly reordered copy is produced while keeping the original unchanged.
arr_ = np.array([10, 20, 30, 40, 50, 60])
a = np.random.permutation(arr_)
np.random.shuffle(arr_)
print(a)
print(arr_)


[40 50 60 30 20 10]
[20 40 50 60 30 10]


In [12]:
# 13. Generate 6 equally spaced values between 0 and 100, including both endpoints
arr = np.linspace(0,100,6)
print(arr)

[  0.  20.  40.  60.  80. 100.]


In [13]:
#14)# 14. Arrange the array into a 3 x 4 matrix, then convert the matrix back into a single 1D array
arr = np.arange(1,13).reshape((3,4))
print(arr)
print("-----------------")
print(np.ravel(arr))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# 15. Change rows into columns and columns into rows. Also create a 3-dimensional NumPy array.
arr = np.arange(1,13).reshape((3,4))
print(arr)
print("------------------------")
a = np.transpose(arr)
print(a)
print("----------------------")
arr = np.arange(1,13).reshape((2,2,3))
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
----------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# 16. Convert the data type to float
arr = np.array([10,20,30,40,50])
result=arr.astype(float)
print(result)


[10. 20. 30. 40. 50.]


In [14]:
# 17. Retrieve 50, retrieve the last row, retrieve the first two columns, and change 80 to 800.
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr)
print("-------------------")
print(arr[1,1])
print("---------------")
print(arr[2])
print("-------------------------")
print(arr[0])
print(arr[1])
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print("-------------------")
arr[2, 1] = 800
print(arr)


[[10 20 30]
 [40 50 60]
 [70 80 90]]
-------------------
50
---------------
[70 80 90]
-------------------------
[10 20 30]
[40 50 60]
-------------------
[[ 10  20  30]
 [ 40  50  60]
 [ 70 800  90]]


In [15]:
# 18. Add 25 between 20 and 30, remove 40, and find the total, smallest value, largest value, and average of the resulting array.
arr = np.array([10, 20, 30, 40, 50])
arr = np.insert(arr, 2, 25)
print(arr)
arr = np.delete(arr, 3)
print(arr)
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))

[10 20 25 30 40 50]
[10 20 25 40 50]
145
10
50
29.0


In [16]:
# 19. Find the variance, standard deviation, 25th percentile, 75th percentile, position of the highest mark, position of the lowest mark, and calculate the base-10 logarithm of each value.
marks = np.array([45, 56, 67, 72, 81, 90, 95])
print(np.var(marks))
print(np.std(marks))
print(np.percentile(marks, 25))
print(np.percentile(marks, 75))
print(np.argmax(marks))
print(np.argmin(marks))
print(np.log10(marks))

277.63265306122446
16.662312356369522
61.5
85.5
6
0
[1.65321251 1.74818803 1.8260748  1.8573325  1.90848502 1.95424251
 1.97772361]


In [17]:
# 20. Combine A and B into one continuous array, arrange A and B one below the other,
# arrange A and B along a newly created dimension, combine all three arrays vertically,
# combine all three arrays horizontally, and divide the combined 1D array into 3 equal parts.
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.array([7, 8, 9])
print(np.concatenate((A, B)))
print("-------------------")
print(np.vstack((A, B)))
print("-------------------")
print(np.stack((A, B)))
print("-------------------")
print(np.vstack((A, B, C)))
print("-------------------")
print(np.hstack((A, B, C)))
print("-------------------")
arr = np.concatenate((A, B, C))
print(np.split(arr, 3))

[1 2 3 4 5 6]
-------------------
[[1 2 3]
 [4 5 6]]
-------------------
[[1 2 3]
 [4 5 6]]
-------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------------
[1 2 3 4 5 6 7 8 9]
-------------------
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
